import type { AnalysisNode, AnalysisOutput, AnalysisSummary, Insight } from '../../engine/types'

// Mock data shaped like real engine output. Use this for viz development
// until the engine is wired in. Replace with real data in integration phase.

const mockInsights: Insight[] = [
  {
    type: 'null_tax',
    path: 'root.adverse_events[].mechanism_of_action',
    severity: 'high',
    message: 'mechanism_of_action is null 65% of the time. Making it optional saves 18 tok/instance.',
    detail: 'This field has a fill rate of 0.35. When null, you still pay for the field name and null literal. Removing it from the schema when not needed saves structural overhead.',
    savings_tokens: 18,
    savings_usd_per_10k: 1.80,
  },
  {
    type: 'array_repetition_tax',
    path: 'root.endpoints[]',
    severity: 'high',
    message: 'Field names in endpoints[] repeat 2.6x per instance, costing 84 tokens in repetition.',
    detail: 'Each array item repeats 7 field names. With an average of 2.6 items, the first instance pays for the names once, but subsequent items pay again.',
    savings_tokens: 84,
    savings_usd_per_10k: 8.40,
  },
  {
    type: 'hollow_object',
    path: 'root.endpoints[].confidence_interval',
    severity: 'medium',
    message: 'confidence_interval is 72% structural overhead. 18 of 25 tokens are field names and braces.',
    detail: 'This object has only two numeric fields (lower, upper) but pays for object braces, field names, and commas each time.',
    savings_tokens: 12,
    savings_usd_per_10k: 1.20,
  },
  {
    type: 'null_tax',
    path: 'root.funding_source',
    severity: 'medium',
    message: 'funding_source is null 60% of the time. Making it optional saves 8 tok/instance.',
    detail: 'This field produces null values more often than not. The structural cost of emitting the field name and null is wasted.',
    savings_tokens: 8,
    savings_usd_per_10k: 0.80,
  },
  {
    type: 'boilerplate',
    path: 'root.study_design',
    severity: 'low',
    message: 'study_design has 4 unique values across 13 instances. Consider replacing with an enum.',
    detail: 'Low value diversity (0.31) suggests this field is effectively an enum. Defining it as such in the schema improves extraction quality.',
    savings_tokens: 3,
    savings_usd_per_10k: 0.30,
  },
]

function s(avg: number, spread: number = 0.3): { avg: number; min: number; max: number; p50: number; p95: number } {
  const min = Math.round(avg * (1 - spread))
  const max = Math.round(avg * (1 + spread))
  const p50 = Math.round(avg * 0.95)
  const p95 = Math.round(avg * 1.4)
  return { avg, min, max, p50, p95 }
}

export const mockTree: AnalysisNode = {
  name: 'root',
  path: 'root',
  depth: 0,
  type: 'object',
  tokens: { total: s(847), schema_overhead: 312, value_payload: 438, null_waste: 97 },
  fill_rate: 1.0,
  instance_count: 13,
  array_stats: null,
  string_stats: null,
  examples: [],
  cost: { per_instance: 0.00847, total_corpus: 0.110 },
  children: [
    {
      name: 'pmid',
      path: 'root.pmid',
      depth: 1,
      type: 'string',
      tokens: { total: s(12), schema_overhead: 4, value_payload: 8, null_waste: 0 },
      fill_rate: 1.0,
      instance_count: 13,
      array_stats: null,
      string_stats: { avg_length: 8, value_diversity: 1.0, unique_count: 13 },
      examples: ['12345678', '23456789', '34567890', '45678901', '56789012'],
      cost: { per_instance: 0.00012, total_corpus: 0.0016 },
      children: [],
    },
    {
      name: 'title',
      path: 'root.title',
      depth: 1,
      type: 'string',
      tokens: { total: s(28), schema_overhead: 4, value_payload: 24, null_waste: 0 },
      fill_rate: 1.0,
      instance_count: 13,
      array_stats: null,
      string_stats: { avg_length: 52, value_diversity: 1.0, unique_count: 13 },
      examples: ['Effects of Drug A on Blood Pressure', 'Efficacy of Drug B in Type 2 Diabetes Management'],
      cost: { per_instance: 0.00028, total_corpus: 0.0036 },
      children: [],
    },
    {
      name: 'year',
      path: 'root.year',
      depth: 1,
      type: 'number',
      tokens: { total: s(5), schema_overhead: 3, value_payload: 2, null_waste: 0 },
      fill_rate: 1.0,
      instance_count: 13,
      array_stats: null,
      string_stats: null,
      examples: [2023, 2022, 2024],
      cost: { per_instance: 0.00005, total_corpus: 0.00065 },
      children: [],
    },
    {
      name: 'population',
      path: 'root.population',
      depth: 1,
      type: 'object',
      tokens: { total: s(62), schema_overhead: 28, value_payload: 32, null_waste: 2 },
      fill_rate: 1.0,
      instance_count: 13,
      array_stats: null,
      string_stats: null,
      examples: [],
      cost: { per_instance: 0.00062, total_corpus: 0.0081 },
      children: [
        {
          name: 'description',
          path: 'root.population.description',
          depth: 2,
          type: 'string',
          tokens: { total: s(22), schema_overhead: 6, value_payload: 15, null_waste: 1 },
          fill_rate: 0.92,
          instance_count: 13,
          array_stats: null,
          string_stats: { avg_length: 38, value_diversity: 1.0, unique_count: 12 },
          examples: ['Adults aged 40-65 with hypertension', 'Healthy volunteers'],
          cost: { per_instance: 0.00022, total_corpus: 0.0029 },
          children: [],
        },
        {
          name: 'sample_size',
          path: 'root.population.sample_size',
          depth: 2,
          type: 'number',
          tokens: { total: s(8), schema_overhead: 5, value_payload: 2, null_waste: 1 },
          fill_rate: 0.92,
          instance_count: 13,
          array_stats: null,
          string_stats: null,
          examples: [240, 520, 1200, 24, 4200],
          cost: { per_instance: 0.00008, total_corpus: 0.0010 },
          children: [],
        },
      ],
    },
    {
      name: 'endpoints',
      path: 'root.endpoints[]',
      depth: 1,
      type: 'array',
      tokens: { total: s(420), schema_overhead: 168, value_payload: 218, null_waste: 34 },
      fill_rate: 1.0,
      instance_count: 13,
      array_stats: { avg_items: 2.6, min_items: 1, max_items: 4, p95_items: 4 },
      string_stats: null,
      examples: [],
      cost: { per_instance: 0.00420, total_corpus: 0.0546 },
      children: [
        {
          name: 'endpoint_phrase',
          path: 'root.endpoints[].endpoint_phrase',
          depth: 2,
          type: 'string',
          tokens: { total: s(32), schema_overhead: 8, value_payload: 24, null_waste: 0 },
          fill_rate: 1.0,
          instance_count: 34,
          array_stats: null,
          string_stats: { avg_length: 35, value_diversity: 0.85, unique_count: 29 },
          examples: ['systolic blood pressure reduction', 'HbA1c reduction at 24 weeks', 'PASI 90 response at 16 weeks'],
          cost: { per_instance: 0.00032, total_corpus: 0.0042 },
          children: [],
        },
        {
          name: 'point_estimate',
          path: 'root.endpoints[].point_estimate',
          depth: 2,
          type: 'number',
          tokens: { total: s(8), schema_overhead: 6, value_payload: 1, null_waste: 1 },
          fill_rate: 0.74,
          instance_count: 34,
          array_stats: null,
          string_stats: null,
          examples: [-12.5, -1.2, 0.82, 3.2],
          cost: { per_instance: 0.00008, total_corpus: 0.0010 },
          children: [],
        },
        {
          name: 'confidence_interval',
          path: 'root.endpoints[].confidence_interval',
          depth: 2,
          type: 'object',
          tokens: { total: s(25), schema_overhead: 18, value_payload: 4, null_waste: 3 },
          fill_rate: 0.68,
          instance_count: 34,
          array_stats: null,
          string_stats: null,
          examples: [],
          cost: { per_instance: 0.00025, total_corpus: 0.0033 },
          children: [
            {
              name: 'lower',
              path: 'root.endpoints[].confidence_interval.lower',
              depth: 3,
              type: 'number',
              tokens: { total: s(6), schema_overhead: 4, value_payload: 2, null_waste: 0 },
              fill_rate: 1.0,
              instance_count: 23,
              array_stats: null,
              string_stats: null,
              examples: [-15.2, -1.5, 0.71, 2.6],
              cost: { per_instance: 0.00006, total_corpus: 0.00078 },
              children: [],
            },
            {
              name: 'upper',
              path: 'root.endpoints[].confidence_interval.upper',
              depth: 3,
              type: 'number',
              tokens: { total: s(6), schema_overhead: 4, value_payload: 2, null_waste: 0 },
              fill_rate: 1.0,
              instance_count: 23,
              array_stats: null,
              string_stats: null,
              examples: [-9.8, -0.9, 0.95, 3.9],
              cost: { per_instance: 0.00006, total_corpus: 0.00078 },
              children: [],
            },
          ],
        },
        {
          name: 'p_value',
          path: 'root.endpoints[].p_value',
          depth: 2,
          type: 'number',
          tokens: { total: s(7), schema_overhead: 5, value_payload: 1, null_waste: 1 },
          fill_rate: 0.62,
          instance_count: 34,
          array_stats: null,
          string_stats: null,
          examples: [0.001, 0.0001, 0.008, 0.06],
          cost: { per_instance: 0.00007, total_corpus: 0.00091 },
          children: [],
        },
      ],
    },
    {
      name: 'adverse_events',
      path: 'root.adverse_events[]',
      depth: 1,
      type: 'array',
      tokens: { total: s(145), schema_overhead: 62, value_payload: 58, null_waste: 25 },
      fill_rate: 0.62,
      instance_count: 13,
      array_stats: { avg_items: 2.1, min_items: 1, max_items: 3, p95_items: 3 },
      string_stats: null,
      examples: [],
      cost: { per_instance: 0.00145, total_corpus: 0.0189 },
      children: [
        {
          name: 'event',
          path: 'root.adverse_events[].event',
          depth: 2,
          type: 'string',
          tokens: { total: s(12), schema_overhead: 4, value_payload: 8, null_waste: 0 },
          fill_rate: 1.0,
          instance_count: 17,
          array_stats: null,
          string_stats: { avg_length: 18, value_diversity: 0.82, unique_count: 14 },
          examples: ['headache', 'nausea', 'neutropenia', 'gastrointestinal bleeding'],
          cost: { per_instance: 0.00012, total_corpus: 0.0016 },
          children: [],
        },
        {
          name: 'severity',
          path: 'root.adverse_events[].severity',
          depth: 2,
          type: 'string',
          tokens: { total: s(8), schema_overhead: 5, value_payload: 3, null_waste: 0 },
          fill_rate: 1.0,
          instance_count: 17,
          array_stats: null,
          string_stats: { avg_length: 6, value_diversity: 0.18, unique_count: 3 },
          examples: ['mild', 'moderate', 'severe'],
          cost: { per_instance: 0.00008, total_corpus: 0.0010 },
          children: [],
        },
        {
          name: 'mechanism_of_action',
          path: 'root.adverse_events[].mechanism_of_action',
          depth: 2,
          type: 'string',
          tokens: { total: s(24), schema_overhead: 8, value_payload: 10, null_waste: 6 },
          fill_rate: 0.35,
          instance_count: 17,
          array_stats: null,
          string_stats: { avg_length: 42, value_diversity: 1.0, unique_count: 6 },
          examples: ['myelosuppression via DNA intercalation', 'direct inhibition of factor Xa reducing thrombin generation'],
          cost: { per_instance: 0.00024, total_corpus: 0.0031 },
          children: [],
        },
      ],
    },
    {
      name: 'study_design',
      path: 'root.study_design',
      depth: 1,
      type: 'string',
      tokens: { total: s(8), schema_overhead: 6, value_payload: 2, null_waste: 0 },
      fill_rate: 1.0,
      instance_count: 13,
      array_stats: null,
      string_stats: { avg_length: 8, value_diversity: 0.31, unique_count: 4 },
      examples: ['RCT', 'cohort', 'meta-analysis', 'case series', 'retrospective'],
      cost: { per_instance: 0.00008, total_corpus: 0.0010 },
      children: [],
    },
    {
      name: 'funding_source',
      path: 'root.funding_source',
      depth: 1,
      type: 'string',
      tokens: { total: s(14), schema_overhead: 6, value_payload: 5, null_waste: 3 },
      fill_rate: 0.38,
      instance_count: 13,
      array_stats: null,
      string_stats: { avg_length: 32, value_diversity: 1.0, unique_count: 5 },
      examples: ['PharmaCorp Inc', 'NIH Grant R01-AG054321', 'National Heart, Lung, and Blood Institute'],
      cost: { per_instance: 0.00014, total_corpus: 0.0018 },
      children: [],
    },
    {
      name: 'registration_number',
      path: 'root.registration_number',
      depth: 1,
      type: 'string',
      tokens: { total: s(10), schema_overhead: 7, value_payload: 2, null_waste: 1 },
      fill_rate: 0.31,
      instance_count: 13,
      array_stats: null,
      string_stats: { avg_length: 14, value_diversity: 1.0, unique_count: 4 },
      examples: ['NCT00012345', 'NCT04567890', 'CRD42024567890'],
      cost: { per_instance: 0.00010, total_corpus: 0.0013 },
      children: [],
    },
    {
      name: 'limitations',
      path: 'root.limitations',
      depth: 1,
      type: 'string',
      tokens: { total: s(18), schema_overhead: 5, value_payload: 8, null_waste: 5 },
      fill_rate: 0.23,
      instance_count: 13,
      array_stats: null,
      string_stats: { avg_length: 58, value_diversity: 1.0, unique_count: 3 },
      examples: ['Small sample size and short follow-up period limit generalizability', 'Open-label design may introduce ascertainment bias for subjective endpoints'],
      cost: { per_instance: 0.00018, total_corpus: 0.0023 },
      children: [],
    },
  ],
}

export const mockSummary: AnalysisSummary = {
  file_count: 13,
  glob: './fixtures/**/*.json',
  model: 'gpt-4o',
  tokenizer: 'o200k_base',
  output_price_per_1m: 10.0,
  avg_tokens_per_instance: 847,
  cost_per_instance: 0.00847,
  overhead_ratio: 0.368,
  null_waste_ratio: 0.115,
  cost_at_1k: 8.47,
  cost_at_10k: 84.70,
  cost_at_100k: 847.0,
  cost_at_1m: 8470.0,
  top_insights: mockInsights.slice(0, 5),
}

export const mockOutput: AnalysisOutput = {
  schema: 'tokstat/v1',
  summary: mockSummary,
  tree: mockTree,
  insights: mockInsights,
}
