import type { AnalysisNode, AnalysisOutput, AnalysisSummary, CohortedOutput, Insight } from '../../engine/types'

// Mock data shaped like real engine output for a movie corpus.
// Use this for viz development until the engine is wired in.

const mockInsights: Insight[] = [
  {
    type: 'null_tax',
    path: 'root.reviews[].summary',
    severity: 'high',
    message: 'summary is null 35% of the time. Making it optional saves 14 tok/instance.',
    detail: 'This field has a fill rate of 0.65. When null, you still pay for the field name and null literal. Removing it from the schema when not needed saves structural overhead.',
    savings_tokens: 14,
    savings_usd_per_10k: 1.40,
  },
  {
    type: 'array_repetition_tax',
    path: 'root.cast[]',
    severity: 'high',
    message: 'Field names in cast[] repeat 2.8x per instance, costing 96 tokens in repetition.',
    detail: 'Each array item repeats 4 field names. With an average of 2.8 items, the first instance pays for the names once, but subsequent items pay again.',
    savings_tokens: 96,
    savings_usd_per_10k: 9.60,
  },
  {
    type: 'hollow_object',
    path: 'root.box_office',
    severity: 'medium',
    message: 'box_office is 68% structural overhead. 17 of 25 tokens are field names and braces.',
    detail: 'This object has only three numeric fields (opening_weekend, domestic_gross, international_gross) but pays for object braces, field names, and commas each time.',
    savings_tokens: 12,
    savings_usd_per_10k: 1.20,
  },
  {
    type: 'null_tax',
    path: 'root.soundtrack',
    severity: 'medium',
    message: 'soundtrack is null 62% of the time. Making it optional saves 8 tok/instance.',
    detail: 'This field produces null values more often than not. The structural cost of emitting the field name and null is wasted.',
    savings_tokens: 8,
    savings_usd_per_10k: 0.80,
  },
  {
    type: 'boilerplate',
    path: 'root.genre',
    severity: 'low',
    message: 'genre has 5 unique values across 13 instances. Consider replacing with an enum.',
    detail: 'Low value diversity (0.38) suggests this field is effectively an enum. Defining it as such in the schema improves extraction quality.',
    savings_tokens: 3,
    savings_usd_per_10k: 0.30,
  },
]

function s(avg: number, spread: number = 0.3): { avg: number; min: number; max: number; p50: number; p95: number } {
  const min = Math.round(avg * (1 - spread))
  const max = Math.round(avg * (1 + spread))
  const p50 = Math.round(avg * 0.95)
  const p95 = Math.round(avg * 1.4)
  return { avg, min, max, p50, p95 }
}

export const mockTree: AnalysisNode = {
  name: 'root',
  path: 'root',
  depth: 0,
  type: 'object',
  tokens: { total: s(920), schema_overhead: 340, value_payload: 480, null_waste: 100 },
  fill_rate: 1.0,
  instance_count: 13,
  array_stats: null,
  string_stats: null,
  examples: [],
  cost: { per_instance: 0.00920, total_corpus: 0.1196 },
  children: [
    {
      name: 'imdb_id',
      path: 'root.imdb_id',
      depth: 1,
      type: 'string',
      tokens: { total: s(12), schema_overhead: 4, value_payload: 8, null_waste: 0 },
      fill_rate: 1.0,
      instance_count: 13,
      array_stats: null,
      string_stats: { avg_length: 9, value_diversity: 1.0, unique_count: 13 },
      examples: ['tt0111161', 'tt0068646', 'tt0468569', 'tt0071562', 'tt0137523'],
      cost: { per_instance: 0.00012, total_corpus: 0.0016 },
      children: [],
    },
    {
      name: 'title',
      path: 'root.title',
      depth: 1,
      type: 'string',
      tokens: { total: s(28), schema_overhead: 4, value_payload: 24, null_waste: 0 },
      fill_rate: 1.0,
      instance_count: 13,
      array_stats: null,
      string_stats: { avg_length: 24, value_diversity: 1.0, unique_count: 13 },
      examples: ['The Shawshank Redemption', 'The Godfather', 'The Dark Knight'],
      cost: { per_instance: 0.00028, total_corpus: 0.0036 },
      children: [],
    },
    {
      name: 'year',
      path: 'root.year',
      depth: 1,
      type: 'number',
      tokens: { total: s(5), schema_overhead: 3, value_payload: 2, null_waste: 0 },
      fill_rate: 1.0,
      instance_count: 13,
      array_stats: null,
      string_stats: null,
      examples: [1994, 1972, 2008, 2001, 2010],
      cost: { per_instance: 0.00005, total_corpus: 0.00065 },
      children: [],
    },
    {
      name: 'genre',
      path: 'root.genre',
      depth: 1,
      type: 'string',
      tokens: { total: s(8), schema_overhead: 4, value_payload: 4, null_waste: 0 },
      fill_rate: 1.0,
      instance_count: 13,
      array_stats: null,
      string_stats: { avg_length: 6, value_diversity: 0.38, unique_count: 5 },
      examples: ['drama', 'crime', 'action', 'fantasy', 'sci-fi'],
      cost: { per_instance: 0.00008, total_corpus: 0.0010 },
      children: [],
    },
    {
      name: 'production',
      path: 'root.production',
      depth: 1,
      type: 'object',
      tokens: { total: s(68), schema_overhead: 30, value_payload: 36, null_waste: 2 },
      fill_rate: 1.0,
      instance_count: 13,
      array_stats: null,
      string_stats: null,
      examples: [],
      cost: { per_instance: 0.00068, total_corpus: 0.0088 },
      children: [
        {
          name: 'director',
          path: 'root.production.director',
          depth: 2,
          type: 'string',
          tokens: { total: s(18), schema_overhead: 5, value_payload: 12, null_waste: 1 },
          fill_rate: 0.92,
          instance_count: 13,
          array_stats: null,
          string_stats: { avg_length: 16, value_diversity: 0.77, unique_count: 10 },
          examples: ['Frank Darabont', 'Francis Ford Coppola', 'Christopher Nolan', 'Peter Jackson'],
          cost: { per_instance: 0.00018, total_corpus: 0.0023 },
          children: [],
        },
        {
          name: 'budget_usd',
          path: 'root.production.budget_usd',
          depth: 2,
          type: 'number',
          tokens: { total: s(10), schema_overhead: 5, value_payload: 4, null_waste: 1 },
          fill_rate: 0.69,
          instance_count: 13,
          array_stats: null,
          string_stats: null,
          examples: [25000000, 6000000, 185000000, 93000000],
          cost: { per_instance: 0.00010, total_corpus: 0.0013 },
          children: [],
        },
      ],
    },
    {
      name: 'cast',
      path: 'root.cast[]',
      depth: 1,
      type: 'array',
      tokens: { total: s(440), schema_overhead: 180, value_payload: 230, null_waste: 30 },
      fill_rate: 1.0,
      instance_count: 13,
      array_stats: { avg_items: 2.8, min_items: 0, max_items: 5, p95_items: 4 },
      string_stats: null,
      examples: [],
      cost: { per_instance: 0.00440, total_corpus: 0.0572 },
      children: [
        {
          name: 'actor',
          path: 'root.cast[].actor',
          depth: 2,
          type: 'string',
          tokens: { total: s(14), schema_overhead: 4, value_payload: 10, null_waste: 0 },
          fill_rate: 1.0,
          instance_count: 36,
          array_stats: null,
          string_stats: { avg_length: 14, value_diversity: 0.83, unique_count: 30 },
          examples: ['Tim Robbins', 'Morgan Freeman', 'Heath Ledger', 'Leonardo DiCaprio'],
          cost: { per_instance: 0.00014, total_corpus: 0.0018 },
          children: [],
        },
        {
          name: 'role',
          path: 'root.cast[].role',
          depth: 2,
          type: 'string',
          tokens: { total: s(14), schema_overhead: 4, value_payload: 10, null_waste: 0 },
          fill_rate: 1.0,
          instance_count: 36,
          array_stats: null,
          string_stats: { avg_length: 14, value_diversity: 0.97, unique_count: 35 },
          examples: ['Andy Dufresne', 'Don Vito Corleone', 'The Joker', 'Gandalf'],
          cost: { per_instance: 0.00014, total_corpus: 0.0018 },
          children: [],
        },
        {
          name: 'billing_order',
          path: 'root.cast[].billing_order',
          depth: 2,
          type: 'number',
          tokens: { total: s(6), schema_overhead: 5, value_payload: 1, null_waste: 0 },
          fill_rate: 1.0,
          instance_count: 36,
          array_stats: null,
          string_stats: null,
          examples: [1, 2, 3, 4, 5],
          cost: { per_instance: 0.00006, total_corpus: 0.00078 },
          children: [],
        },
        {
          name: 'awards',
          path: 'root.cast[].awards[]',
          depth: 2,
          type: 'array',
          tokens: { total: s(52), schema_overhead: 28, value_payload: 22, null_waste: 2 },
          fill_rate: 0.58,
          instance_count: 36,
          array_stats: { avg_items: 1.4, min_items: 0, max_items: 3, p95_items: 3 },
          string_stats: null,
          examples: [],
          cost: { per_instance: 0.00052, total_corpus: 0.0068 },
          children: [
            {
              name: 'category',
              path: 'root.cast[].awards[].category',
              depth: 3,
              type: 'string',
              tokens: { total: s(10), schema_overhead: 5, value_payload: 5, null_waste: 0 },
              fill_rate: 1.0,
              instance_count: 21,
              array_stats: null,
              string_stats: { avg_length: 18, value_diversity: 0.24, unique_count: 5 },
              examples: ['Best Actor', 'Best Supporting Actor', 'Best Ensemble Cast'],
              cost: { per_instance: 0.00010, total_corpus: 0.0013 },
              children: [],
            },
            {
              name: 'ceremony',
              path: 'root.cast[].awards[].ceremony',
              depth: 3,
              type: 'string',
              tokens: { total: s(12), schema_overhead: 5, value_payload: 7, null_waste: 0 },
              fill_rate: 1.0,
              instance_count: 21,
              array_stats: null,
              string_stats: { avg_length: 16, value_diversity: 0.29, unique_count: 6 },
              examples: ['Academy Awards', 'Golden Globes', 'Screen Actors Guild', 'Saturn Awards'],
              cost: { per_instance: 0.00012, total_corpus: 0.0016 },
              children: [],
            },
            {
              name: 'won',
              path: 'root.cast[].awards[].won',
              depth: 3,
              type: 'boolean',
              tokens: { total: s(5), schema_overhead: 3, value_payload: 2, null_waste: 0 },
              fill_rate: 1.0,
              instance_count: 21,
              array_stats: null,
              string_stats: null,
              examples: [true, false],
              cost: { per_instance: 0.00005, total_corpus: 0.00065 },
              children: [],
            },
          ],
        },
      ],
    },
    {
      name: 'box_office',
      path: 'root.box_office',
      depth: 1,
      type: 'object',
      tokens: { total: s(40), schema_overhead: 26, value_payload: 12, null_waste: 2 },
      fill_rate: 0.62,
      instance_count: 13,
      array_stats: null,
      string_stats: null,
      examples: [],
      cost: { per_instance: 0.00040, total_corpus: 0.0052 },
      children: [
        {
          name: 'opening_weekend',
          path: 'root.box_office.opening_weekend',
          depth: 2,
          type: 'number',
          tokens: { total: s(10), schema_overhead: 7, value_payload: 3, null_waste: 0 },
          fill_rate: 1.0,
          instance_count: 8,
          array_stats: null,
          string_stats: null,
          examples: [727000, 158411483, 72629713, 62785337],
          cost: { per_instance: 0.00010, total_corpus: 0.0013 },
          children: [],
        },
        {
          name: 'domestic_gross',
          path: 'root.box_office.domestic_gross',
          depth: 2,
          type: 'number',
          tokens: { total: s(10), schema_overhead: 7, value_payload: 3, null_waste: 0 },
          fill_rate: 1.0,
          instance_count: 8,
          array_stats: null,
          string_stats: null,
          examples: [28341469, 134966411, 533316061, 315544750],
          cost: { per_instance: 0.00010, total_corpus: 0.0013 },
          children: [],
        },
        {
          name: 'international_gross',
          path: 'root.box_office.international_gross',
          depth: 2,
          type: 'number',
          tokens: { total: s(10), schema_overhead: 7, value_payload: 3, null_waste: 0 },
          fill_rate: 1.0,
          instance_count: 8,
          array_stats: null,
          string_stats: null,
          examples: [30000000, 110000000, 469700000, 556592194],
          cost: { per_instance: 0.00010, total_corpus: 0.0013 },
          children: [],
        },
      ],
    },
    {
      name: 'reviews',
      path: 'root.reviews[]',
      depth: 1,
      type: 'array',
      tokens: { total: s(95), schema_overhead: 42, value_payload: 40, null_waste: 13 },
      fill_rate: 0.46,
      instance_count: 13,
      array_stats: { avg_items: 2.3, min_items: 1, max_items: 3, p95_items: 3 },
      string_stats: null,
      examples: [],
      cost: { per_instance: 0.00095, total_corpus: 0.0124 },
      children: [
        {
          name: 'source',
          path: 'root.reviews[].source',
          depth: 2,
          type: 'string',
          tokens: { total: s(10), schema_overhead: 4, value_payload: 6, null_waste: 0 },
          fill_rate: 1.0,
          instance_count: 14,
          array_stats: null,
          string_stats: { avg_length: 12, value_diversity: 0.29, unique_count: 4 },
          examples: ['Rotten Tomatoes', 'Metacritic', 'Roger Ebert', 'Festival Jury'],
          cost: { per_instance: 0.00010, total_corpus: 0.0013 },
          children: [],
        },
        {
          name: 'score',
          path: 'root.reviews[].score',
          depth: 2,
          type: 'number',
          tokens: { total: s(6), schema_overhead: 4, value_payload: 2, null_waste: 0 },
          fill_rate: 1.0,
          instance_count: 14,
          array_stats: null,
          string_stats: null,
          examples: [91, 92, 100, 87, 74],
          cost: { per_instance: 0.00006, total_corpus: 0.00078 },
          children: [],
        },
        {
          name: 'summary',
          path: 'root.reviews[].summary',
          depth: 2,
          type: 'string',
          tokens: { total: s(22), schema_overhead: 5, value_payload: 12, null_waste: 5 },
          fill_rate: 0.65,
          instance_count: 14,
          array_stats: null,
          string_stats: { avg_length: 42, value_diversity: 1.0, unique_count: 9 },
          examples: ['A visually breathtaking and emotionally powerful adaptation', 'Smart, innovative, and thrilling'],
          cost: { per_instance: 0.00022, total_corpus: 0.0029 },
          children: [],
        },
      ],
    },
    {
      name: 'rating',
      path: 'root.rating',
      depth: 1,
      type: 'string',
      tokens: { total: s(7), schema_overhead: 4, value_payload: 2, null_waste: 1 },
      fill_rate: 0.69,
      instance_count: 13,
      array_stats: null,
      string_stats: { avg_length: 3, value_diversity: 0.22, unique_count: 2 },
      examples: ['R', 'PG-13'],
      cost: { per_instance: 0.00007, total_corpus: 0.00091 },
      children: [],
    },
    {
      name: 'distributor',
      path: 'root.distributor',
      depth: 1,
      type: 'string',
      tokens: { total: s(12), schema_overhead: 5, value_payload: 5, null_waste: 2 },
      fill_rate: 0.31,
      instance_count: 13,
      array_stats: null,
      string_stats: { avg_length: 18, value_diversity: 0.75, unique_count: 3 },
      examples: ['New Line Cinema', 'Warner Bros. Pictures', 'StreamFlix'],
      cost: { per_instance: 0.00012, total_corpus: 0.0016 },
      children: [],
    },
    {
      name: 'soundtrack',
      path: 'root.soundtrack',
      depth: 1,
      type: 'object',
      tokens: { total: s(32), schema_overhead: 20, value_payload: 8, null_waste: 4 },
      fill_rate: 0.23,
      instance_count: 13,
      array_stats: null,
      string_stats: null,
      examples: [],
      cost: { per_instance: 0.00032, total_corpus: 0.0042 },
      children: [
        {
          name: 'composer',
          path: 'root.soundtrack.composer',
          depth: 2,
          type: 'string',
          tokens: { total: s(10), schema_overhead: 5, value_payload: 5, null_waste: 0 },
          fill_rate: 1.0,
          instance_count: 3,
          array_stats: null,
          string_stats: { avg_length: 12, value_diversity: 0.67, unique_count: 2 },
          examples: ['Howard Shore', 'Hans Zimmer'],
          cost: { per_instance: 0.00010, total_corpus: 0.0013 },
          children: [],
        },
        {
          name: 'tracks',
          path: 'root.soundtrack.tracks',
          depth: 2,
          type: 'number',
          tokens: { total: s(5), schema_overhead: 4, value_payload: 1, null_waste: 0 },
          fill_rate: 1.0,
          instance_count: 3,
          array_stats: null,
          string_stats: null,
          examples: [18, 20, 12],
          cost: { per_instance: 0.00005, total_corpus: 0.00065 },
          children: [],
        },
        {
          name: 'grammy_nominated',
          path: 'root.soundtrack.grammy_nominated',
          depth: 2,
          type: 'boolean',
          tokens: { total: s(6), schema_overhead: 5, value_payload: 1, null_waste: 0 },
          fill_rate: 1.0,
          instance_count: 3,
          array_stats: null,
          string_stats: null,
          examples: [true],
          cost: { per_instance: 0.00006, total_corpus: 0.00078 },
          children: [],
        },
      ],
    },
  ],
}

export const mockSummary: AnalysisSummary = {
  file_count: 13,
  glob: './fixtures/**/*.json',
  model: 'gpt-4o',
  tokenizer: 'o200k_base',
  output_price_per_1m: 10.0,
  corpus_total_tokens: 11960,  // 920 * 13
  corpus_total_cost: 0.1196,   // 0.00920 * 13
  avg_tokens_per_instance: 920,
  cost_per_instance: 0.00920,
  overhead_ratio: 0.370,
  null_waste_ratio: 0.109,
  cost_at_1k: 9.20,
  cost_at_10k: 92.0,
  cost_at_100k: 920.0,
  cost_at_1m: 9200.0,
  top_insights: mockInsights.slice(0, 5),
}

export const mockOutput: AnalysisOutput = {
  schema: 'tokstat/v1',
  summary: mockSummary,
  tree: mockTree,
  insights: mockInsights,
}

// Create two mock cohorts so the Scope selector is visible in dev mode.
// In production, cohorts are auto-detected from schema fingerprints.
const basicSummary: AnalysisSummary = {
  ...mockSummary,
  file_count: 8,
  corpus_total_tokens: 7360,
  corpus_total_cost: 0.0736,
}

const verboseSummary: AnalysisSummary = {
  ...mockSummary,
  file_count: 5,
  corpus_total_tokens: 4600,
  corpus_total_cost: 0.046,
}

const basicOutput: AnalysisOutput = {
  schema: 'tokstat/v1',
  summary: basicSummary,
  tree: mockTree,
  insights: mockInsights.slice(0, 3),
}

const verboseOutput: AnalysisOutput = {
  schema: 'tokstat/v1',
  summary: verboseSummary,
  tree: mockTree,
  insights: mockInsights,
}

export const mockCohortedOutput: CohortedOutput = {
  schema: 'tokstat/v1',
  cohorts: [
    {
      id: 'basic-schema',
      label: 'imdb_id, title, cast, box_office (8 files)',
      file_count: 8,
      file_indices: [0, 1, 2, 3, 4, 5, 6, 7],
    },
    {
      id: 'verbose-schema',
      label: 'imdb_id, title, cast, production, reviews (5 files)',
      file_count: 5,
      file_indices: [8, 9, 10, 11, 12],
    },
  ],
  combined: mockOutput,
  per_cohort: {
    'basic-schema': basicOutput,
    'verbose-schema': verboseOutput,
  },
}
